### ISSUE TITLE
Any plans or can we remove this?

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/docker-base-bistro-image-builder#1]
Hi @JanMikes , 

I'm going through unused repositories.
Got any plans to use this or can be remove it? :)

**Comment by JanMikes** [comment]
Hi @TomasVotruba i actively use this repo and is involved in rectorbot infrastructure. It is good as it is and currently does not need any tweaks.

This repo serves as package builder: https://github.com/rectorphp/docker-base-bistro-image-builder/packages/409772

Since the only place where it is used is my private server and it is cached, it shows 0 downloads 😄

**Comment by JanMikes** [comment]
If curious, check https://github.com/rectorphp/docker-base-bistro-image-builder/blob/master/.github/workflows/public-docker-image.yml 

It compiles C library, wraps to Docker image and publishes it to github package registry

**Comment by TomasVotruba** [comment]
I see :)
